flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/haskell-servant/servant-quickcheck
    commit: 343f55f61a98900410b2e97cc7cea6dee25b5eb7
  extra-dep: true
- location:
    git: https://www.github.com/mattjbray/elm-export
    commit: 8868c1f09597f44c2e18e014cd9fbcf8320c3fea
  extra-dep: True
- location:
    git: https://www.github.com/mattjbray/servant-elm
    commit: 58ce4226b85b2c07ecfdb761d9b4eca33f6654a5
  extra-dep: True
extra-deps:
- servant-0.8.1
- servant-client-0.8.1
- servant-docs-0.8.1
- servant-js-0.8.1
- servant-mock-0.8.1
- servant-server-0.8.1
- servant-swagger-0.8.1
- servant-foreign-0.8.1
resolver: lts-6.17
