flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/haskell-servant/servant-quickcheck
    commit: 343f55f61a98900410b2e97cc7cea6dee25b5eb7
  extra-dep: true
- location:
    git: https://www.github.com/jcberentsen/elm-export
    commit: 894649652bd8c467b77ce761ba55627700736ab3
  extra-dep: True
- location:
    git: https://www.github.com/mattjbray/servant-elm
    commit: 58ce4226b85b2c07ecfdb761d9b4eca33f6654a5
  extra-dep: True
extra-deps:
- servant-0.8.1
- servant-client-0.8.1
- servant-docs-0.8.1
- servant-js-0.8.1
- servant-mock-0.8.1
- servant-server-0.8.1
- servant-swagger-1.0.3
- servant-foreign-0.8.1
resolver: lts-6.17
